# Site settings
title: "Sandip Nikale"
email: nikalesandip@yahoo.com
description: "Sandip's Blogs"
baseurl: https://sandipnikale.github.io/blogss/
url: https://sandipnikale.github.io/blogss/
title_description: "Hi I'm Sandip. I am Red Hat Certified Engineer  & I work at ESDS Nasik. I contribute to OpenSource in any possible way"
title_image: "https://external-preview.redd.it/V77U-n3OuvNr2I14hRYUcyXBJ1C9dEMV3HUt3dAIViw.png?auto=webp&s=20d05cf394bd203741ddfdffa904af94fdd90544"
google_analytics: "UA-20365477-4"
disqus_account: sandip
github_repository: https://sandipnikale.github.io/blogss
addthis_id: ra-5c1cc27c740923bd
post_limit: 20

# Social usernames/URLs
twitter_username: 
github_username:  
linkedin_link: https://sandipnikale.github.io/blogss
google_plus_link: https://sandipnikale.github.io/blogss
stackoverflow_link: https://sandipnikale.github.io/blogss

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://sandipnikale.github.io/linux\">Sandip </a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/sandipnikale\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
